

const photosInfo = [
  {
    "firstName": "Aditya",
    "lastName": "Gyawali",
    "title": "Software Developer Trainee",
    "nationality": "Nepalese",
    "src": "aditya.jpg",
    "alt": "Aditya",
    "skills": ["HTML", "CSS", "Bootstrap", "JavaScript", "JQuery", "React"],
    "whySofterDeveloper": "Because you can work on any part of the world with the knowledge you have no language barrier n stuff",
    "longTermVision": "working on projects from home",
    "motivatesMe": "€",
    "favoriteQuote": "It will take time, but it will happen",
    "joinedOn": "22-1-2017"
  },
  {
    "firstName": "Rasbin",
    "lastName": "Rijal",
    "title": "Junior Developer",
    "nationality": "Nepalese",
    "src": "rasbin.jpg",
    "alt": "Rasbin",
    "skills": ["HTML", "CSS", "Bootstrap", "JavaScript", "JQuery", "React", "PHP", "MySQL"],
    "whySofterDeveloper": "Limitless opportunities of creation",
    "longTermVision": "IT Service Manager",
    "motivatesMe": "Books",
    "favoriteQuote": "Everything is possible", "joinedOn": "04-12-2017"
  },
  {
    "firstName": "Asabeneh",
    "lastName": "Yetayeh",
    "title": "Programming Teacher",
    "nationality": "Ethiopian",
    "src": "asabeneh.jpg",
    "alt": "Asabeneh",
    "skills": ["HTML5", "CSS3", "JavaScript", "React", "Node", "MongoDB", "Python", "R", "D3.js"],
    "whySofterDeveloper": "Being a software developer created an opportunity to work on projects from different discipline.",
    "longTermVision": "I like to be a full stack developer in modern web Technologies and a data scientist.", "motivatesMe": "",
    "favoriteQuote": "Education is a gift that can none take away.",
    "joinedOn": "04-12-2017"
  },
  {
    "firstName": "Senad",
    "lastName": "Maljici",
    "title": "Junior Javascript Developer ",
    "nationality": "Serbian",
    "src": "senad.jpg",
    "alt": "Senad",
    "skills": ["HTML5", "CSS3", "Javascript", "PHP", "SQL"],
    "whySofterDeveloper": "Making money while having fun",
    "longTermVision": "Building a great company which will change the world for the better",
    "motivatesMe": "Hamburgers", "favoriteQuote": "Every strike brings me closer to the next home run-Babe Ruth", "joinedOn": "04.12.2017"
  },
  {
    "firstName": "Niloofar",
    "lastName": "Motamed",
    "title": "Junior developer",
    "nationality": "Iranian",
    "src": "niloofar.jpg",
    "alt": "Niloo",
    "skills": ["HTML", "CSS", "JS", "React", "Redux"],
    "whySofterDeveloper": "To build a decent career for myself, something that I will enjoy doing everyday",
    "longTermVision": "Being a skillful developer who works remotely and also runs her startup company from Nice",
    "motivatesMe": "traveling around the world, reading good literature, fine arts, making money to do these",
    "favoriteQuote": "An eye for an eye, leaves the whole world blind", "joinedOn": "04.12.2017"
  },
  {
    "firstName": "Sanjog",
    "lastName": "Shrestha",
    "title": "Junior Developer",
    "nationality": "Nepali",
    "src": "sanjog.jpg",
    "alt": "Sanjog",
    "skills": ["HTML", "CSS", "JavaScript", "React", "Redux"],
    "whySofterDeveloper": "Interest",
    "longTermVision": "Professional Software Developer",
    "motivatesMe": "",
    "favoriteQuote": "",
    "joinedOn": "04.12.2017"
  },
  {
    "firstName": "Pragya",
    "lastName": "Gupta",
    "title": "Junior Web Developer", "nationality": "Indian",
    "src": "pragya.jpg", "alt": "Pragya",
    "skills": ["HTML", "CSS", "JavaScript", "React", "Redux"],
    "whySofterDeveloper": "Engineering Creativity",
    "longTermVision": "Entrepreneur",
    "motivatesMe": "I Love Coding",
    "favoriteQuote": "Work is worship",
    "joinedOn": "04-12-2017"
  },
  {
    "firstName": "Mohammed",
    "lastName": "Mansoor",
    "title": "Junior web developer",
    "nationality": "Iraq",
    "src": "mohammed_mansoor.jpg",
    "alt": "Mohammed Mansoor",
    "skills": ["HTML", "CSS", "JavaScript", "React", "Redux", "Angular", "Nodejs", "MongoDB", "Python"],
    "whySofterDeveloper": "",
    "longTermVision": "",
    "motivatesMe": "",
    "favoriteQuote": "",
    "joinedOn": "04-12-2017"
  },
  {
    "firstName": "Hoang Anh",
    "lastName": "Vo",
    "title": "Junior Web Developer",
    "nationality": "Vietnamese",
    "src": "anh_vo.jpg",
    "alt": "Anh Vo",
    "skills": ["Javascript", "Reactjs", "Reduxjs", "Nodejs", "HTML5", "CSS3", "React-router", "Bootstrap", "Jquery", "PHP", "SQL", "Photoshop"],
    "whySofterDeveloper": "Thanks to programming and engineering having the instant feedback, I could continuously move forward in this world. If you dont go forward you gonna fall back",
    "longTermVision": "Yoga+IT entrepreneur",
    "motivatesMe": "Music, books, sharing knowledge, achieve the goals with my team",
    "favoriteQuote": "IF YOU WANT TO GET MORE, BECOME MORE",
    "joinedOn": "04.12.2017"
  },
  {
    "firstName": "Tareq",
    "lastName": "Mahmud",
    "title": "Aspiring full stack developer",
    "nationality": "Bangladeshi",
    "src": "tareq.jpg", "alt": "Tareq", "skills": ["Javascript", "Reactjs", "Reduxjs", "Node.js", "HTML5", "CSS3", "React-router", "Bootstrap", "Jquery"],
    "whySofterDeveloper": "Passion for tech and business",
    "longTermVision": "Become a fullstack developer",
    "motivatesMe": "Solving everyday problems by using technologies",
    "favoriteQuote": "Do not go gentle into the good night",
    "joinedOn": "31.01.2018"
  },
  {
    "firstName": "Mohamed",
    "lastName": "Musse Farah",
    "title": "Junior Web Developer",
    "nationality": "Finland,Somali",
    "src": "mohammed_rashid.jpg",
    "alt": "Mohamed",
    "skills": ["HTML", "CSS", "Javascript"],
    "whySofterDeveloper": "Because i’m intrested to learn the tech industry and software developer is the start of it.",
    "longTermVision": "Hopefully i could succeed and 1 day i could start my own company.And become a business man.",
    "motivatesMe": "Gaining new knowledge.",
    "favoriteQuote": "Say hello to my little friend.",
    "joinedOn": "04.12.2017"
  },
  {
    "firstName": "Abdirahman",
    "lastName": "Ali",
    "title": "Junior Web Developer",
    "Nationality": "Somali",
    "src": "abdirahmaan_ali.jpg",
    "alt": "Abdirahman",
    "skills": ["HTML", "CSS", "Javascript", "Jqeury"],
    "whySofterDeveloper": "To become an intelligent",
    "longTermVision": "To improve my skills further and become good enough ",
    "motivatesMe": "Always learning new stuff", "favoriteQuote": "",
    "joinedOn": "04-12-2017"
  },
  {
    "firstName": "Sandhya",
    "lastName": "Mahat",
    "title": "Junior Web Developer",
    "nationality": "Nepalese",
    "src": "sandhya.jpg",
    "alt": "Sandhya",
    "skills": ["HTML5", "CSS3", "JavaScript", "React", "React/Redux", "SQL", "PHP"],
    "whySofterDeveloper": "Because future depends on technology and a software developer manipulates technology.",
    "longTermVision": "CEO of a successful IT company providing jobs to millions",
    "motivatesMe": "Learning new set of skills while accomplishing real-life projects",
    "favoriteQuote": "The secret of your success is determined by your daily agenda.",
    "joinedOn": "04-12-2017"
  },
   {
    "firstName": "Olujuwon Ayoseyi",
    "lastName": "Alabi", "title": "Developer",
    "nationality": "Nigeria",
    "src": "olujuwon.jpg",
    "alt": "Olujuwon Ayoseyi",
    "skills": ["HTML5", "CSS3", "Javascript", "Jquery", "Bootstrap", "React.js", "Redux", "Node.js", "NPM", "DOM", "Regex", "React-router"],
    "whySofterDeveloper": "Good skill to have",
    "motivatesMe": "Good food",
    "longTermVision": "Entrepreneur",
    "favoriteQuote": "..I cant please you...",
    "joinedOn": "04-12-2017"
  },
  {
    "firstName": "Hussen",
    "lastName": "Asir",
    "title": "Junior devoleper",
    "nationality": "Finnish",
    "src": "hussen.jpg",
    "alt": "Hussen Asir",
    "skills": ["HTML", "CSS", "JavaScript", "Jquery"],
    "whySofterDeveloper": "to be able to do more with my creativity",
    "longTermVision": "Entrepreneur",
    "motivatesMe": "being closer to my goals after each step",
    "favoriteQuote": "what doesent kill you makes you stronger",
    "joinedOn": "04-12-2017"
  }
]

export default photosInfo;